### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by skim245** [JinmiaoChenLab/SEDR#4]
Dear authors,

I've installed SEDR == 1.0.0 
and get an error message below. 

`AttributeError: module 'SEDR' has no attribute 'graph_construction'`

any suggestions? 

Thank you in advance!

**Comment by skim245** [comment]
@Xuhang01 whilst trying to re-install SEDR, I get ImportError
`ImportError: cannot import name 'res_search_fixed_clus' from 'SEDR.clustering_func' 
(/Users/envs/SEDR_Env2/lib/python3.8/site-packages/SEDR-1.0.0-py3.8.egg/SEDR/clustering_func.py)

I've used Anaconda installation method suggested in the link 
https://sedr.readthedocs.io/en/latest/Installation.html

**Comment by Xuhang01** [comment]
@skim245  Hi, I have solved this error: `ImportError: cannot import name 'res_search_fixed_clus' from 'SEDR.clustering_func'. This is caused by an imcomplete update. I have revised the code accordingly. Please try again to see if it works for you. 

But I have no idea about this one: AttributeError: module 'SEDR' has no attribute 'graph_construction'. Could you provide more message? Such as which command or code generate this error.

**Comment by skim245** [comment]
@Xuhang01 updates in the code solved all the issues! both of the errors were due to incomplete installation of SEDR.
